<h1 class="text-center">Admin List</h1>
<a href="?page=adminadd" class="btn btn-primary m-1">Add Picture</a>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Source</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Author</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($pictures as $pic) : ?>
    
    <tr>
      <th scope="row"><?= $pic['id'] ?></th>
      <td><img width="80" src="<?= $pic['src'] ?>" alt="<?= $pic['title'] ?>"></td>
      <td><?= $pic['title'] ?></td>
      <td><?= $pic['description'] ?></td>
      <td><?= $pic['author'] ?></td>
      <td>

        <!--BUTTON UPDATE-->
        <a href="?page=adminupdate&id=<?php echo $pic['id'];?>" class="btn btn-warning m-1">Update</a>

        <!--BUTTON DELETE-->
        <a href="?page=admindelete&id=<?php echo $pic['id'];?>" class="btn btn-danger m-1" onClick='return yourConfirm(<?=$pic['id']?>);'>Delete</a>
      </td>
    </tr>
  <?php endforeach ?>
  </tbody>
</table>

<a href="?page=adminadd" class="btn btn-primary m-1">Add Picture</a>

<script type="text/javascript">
function yourConfirm() {
    if (confirm("Êtes-vous sûr de vouloir supprimer l'image ?")) {
        alert("Vous avez supprimé l'image.");
        return true;
    } else {
        alert("Vous avez annulé la suppression.");
        return false;
    }
}
</script>
