<h1>
    Mail
</h1>

<form method="POST">
<div class="container">
        <div class="mb-3">
            <label for="subject" class="form-label">Subject</label>
            <input type="text" class="form-control" name="Subject" id="subject" required>
        </div>
        <div class="mb-3">
            <label for="body" class="form-label">Body</label>
            <input type="text" class="form-control" name="Body" id="body" required>
        </div>
        <div class="mb-3">
            <label for="message">Your message</label>
            <textarea class="form-control" id="message" name="message" rows="3" required></textarea>
        </div>
        <input type="submit" class="btn btn-primary text-center" name="Submit" value="Submit">
    </div>
</form>