<h1 class="mb-3 text-center">
    CONTACT
</h1>

<p class="mb-3 text-center">
    N'hésitons pas à prendre contact !
</p>

<form method="POST">
    <div class="container">
        <div class="mb-3">
            <label for="email" class="form-label">Email address</label>
            <input type="email" class="form-control" name="mail" id="email" required>
        </div>
        <div class="mb-3">
            <label for="password" class="form-label">Password</label>
            <input type="password" class="form-control" name="password" id="password" required>
        </div>
        <div class="mb-3">
            <label for="message">Your message</label>
            <textarea class="form-control" id="message" name="message" rows="3" required></textarea>
        </div>
        <input type="submit" class="btn btn-primary text-center" name="Submit" value="Submit">
    </div>
</form>